name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  repository_dispatch:
    types: [update_contentful]

env:
  NODE_VERSION: "14.x"

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed') || github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - run: npm ci
      - run: npm run generate
      - name: move swa config
        run: mv staticwebapp.config.json ./dist

      - uses: actions/upload-artifact@v2
        with:
          name: vuedist
          path: ./dist/*

  deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed' && github.actor != 'dependabot[bot]')
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Job
    steps:
      - name: Download publish files
        uses: actions/download-artifact@v2
        with:
          name: vuedist
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_CLIFF_0AC6CB51E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ""
          skip_app_build: true
        env:
          CTF_SPACE: ${{ secrets.CTF_SPACE }}
          CTF_ACCESS_TOKEN: ${{ secrets.CTF_ACCESS_TOKEN }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WITTY_CLIFF_0AC6CB51E }}
          action: "close"
